-- MySQL Script generated by MySQL Workbench
-- jue 14 jun 2018 11:32:16 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cajero
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cajero` ;

-- -----------------------------------------------------
-- Schema cajero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cajero` DEFAULT CHARACTER SET utf8 ;
USE `cajero` ;

-- -----------------------------------------------------
-- Table `cajero`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cajero`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `cajero`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cajero`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cajero`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `cajero`.`Cuenta` (
  `idCuenta` INT NOT NULL,
  `Saldo` DECIMAL NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cajero`.`CC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cajero`.`CC` ;

CREATE TABLE IF NOT EXISTS `cajero`.`CC` (
  `idCC` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  PRIMARY KEY (`idCC`, `Cliente_idCliente`, `Cuenta_idCuenta`),
  INDEX `fk_CC_Cliente_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_CC_Cuenta1_idx` (`Cuenta_idCuenta` ASC),
  CONSTRAINT `fk_CC_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `cajero`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CC_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `cajero`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
